# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/tti
    REF boost-1.65.1
    SHA512 acf0e3057a721107720e5ea15cf8505bd5362e333016c611bcfb8fb514d01675fcea4a1b87e013c89fc7224bcd37b3d0b4ab253f4e7730717d1c63a765068407
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
