# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/type_traits
    REF boost-1.65.1
    SHA512 25168f9fddfb7a8f77c81850f2c86e391af8cb120c35a9ff47d5474b4cd32dc65059d234e42e4e3a78f88d9368a89ad434de996eab3d2ec2d169aaf2fc63ce44
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
