# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/align
    REF boost-1.65.1
    SHA512 8c89f4eaf5d9946821ad78b4395f4ce8f86c4c96dba32e92c583feffebf36da626dcff428efd8781750dc169b32c9b17c4711834af3ed2f6ca5e287c4e0b5706
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
