# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/odeint
    REF boost-1.65.1
    SHA512 75d4fcd2ac2d99c4bc673a1bff226ff91581c6cb50ec504fbe3f233d0e1f947b3ef56130101e649d531b02e7584a87d4dac918d3a37ec37a896c77c407b14997
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
