# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/compatibility
    REF boost-1.65.1
    SHA512 4ae0db61d1026228eaeb7ff8e149823f01fb23e57b03767ff92c2c4be37f493a262f93930b41642d596c15d35c96c07aeb44eaec2c6876c2f17c7e8d8b3c9de2
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
