# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/functional
    REF boost-1.65.1
    SHA512 852b11cc08a672008c8479e64a6a62ea2905e68cff29401bed651465084b2b48c6527dfe2fb462ab4dce4ec227c770ed4ff53482422e4caca75fdf3b5c0b4de2
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
