# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/predef
    REF boost-1.65.1
    SHA512 0ead4a73c20d2d95f44de71665206b729c135942a61202da657751b8725fb8613c0e7afebbb942f49403d4034524a2763c807460833753e960b8fb31b9fbbd60
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
