# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/exception
    REF boost-1.65.1
    SHA512 438be33f7b2ac928c104bc379c7e6ccd26f3471e15cd526bd2f4024aed3a30fe8bb102ca324893c8ff0669b884d10ec42bb1c360f306abbd0bc3c557f972a8c7
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
