# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/type_index
    REF boost-1.65.1
    SHA512 6987ee63703f47daaa295e8ec245dd94607d8b16854f77b534a6f0148a88cbc0af9db79788f25c2b8b5485df00007ceceb610271eaba21c353e340b033370e1c
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
