# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/smart_ptr
    REF boost-1.65.1
    SHA512 a4ea4d391a77ba19ab9a95992640314d6d169b57f2ba1b95b08555af3bc36cc5860c405bd6190ce838229f1893bbc57079706dc02f142b1cbf48327cf021fac7
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
