# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/stacktrace
    REF boost-1.65.1
    SHA512 cf69a5281811356a3dd842fbbc17e4994aef8173a0e562ca65938798de61fd288cd59265b20a8b27405574ecbdabd79fc750eedc2f1c27cf2dd89c3542cb90f9
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
