# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/interval
    REF boost-1.65.1
    SHA512 f15ebbb88f46c2e7f49fab573d4980d7c164058947c20a74042c9abcbfd761cf14a4f3be264acb71cd4ddb70b3757ca923fc3a2a4f7a9e10b159b73b586f4126
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
