# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/utility
    REF boost-1.65.1
    SHA512 b32804668c175bde5520b1de37d897384577d65b75b9be2e998ba211bd9cc8aad3fe3cf38984c72fa1a0c9cc93de502b2b413a13afaf820471420b5ebefa5344
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
