# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/python
    REF boost-1.65.1
    SHA512 6661e2acfbc26d213ab59d188397bf143bbc763c93ad25149e53b1f87dc82c68bd8453008e9c00e2a427d59f73294fed0ff83def624a6c0ead824f72eb863ca0
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
