# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/random
    REF boost-1.65.1
    SHA512 4e9b4d1760157f548dbd6596b91e44bfb4bb84cfb2f3a3916096e5e9623f6121e774508e4eb83ed834990751f409b751940a5d2189cc51de7579734788b1c97f
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
