# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/fiber
    REF boost-1.65.1
    SHA512 02c114de09be98ed30d1ff1452004fa3af0b038e985fe193acf3aff56804adfc92c7800f09b5ccac3d208cdb2b5bd122b6d31f9ae083bf21e8e637bd795bbc62
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
