# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/hana
    REF boost-1.65.1
    SHA512 ed5aca7ef21e26cc2c4d6e2ac0dc41be64b8a6b72b07d3a3a888b724e36991611258c848271172ffe45fad740ed03aac50a4baa9fdbfff30dc022044d3b53401
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
