# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/array
    REF boost-1.65.1
    SHA512 fee0cd1f991263edaef1dec668ed34e6495fab54a8fcc0987aa387905df3daf8c746efcb0d52aa7c9820ae186765303b988409250473b18be83dee0d02cc14a7
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
