# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/uuid
    REF boost-1.65.1
    SHA512 d5222c9e597df3d5953a919e8e42c50856318f7e29a46b44d9c4d1ddb7fdf03b9e7d46159bafcd4b299657626863ebcb453b11880be71dac2dd18abf226e9a1d
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
