# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/ratio
    REF boost-1.65.1
    SHA512 410dd5a327b5e121bc3dac5bd48e7588b011f7e09de8f565a4f6ca34234083b786afb5b07d4d778efb98c376f297ff57cd400cedeb872ab05f9f89f05a6c0c86
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
