# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/lexical_cast
    REF boost-1.65.1
    SHA512 66c20509ad4dbc2d7011dcd13664fce033fa20470389d86665984b70f45d6cb4e084c17bd2d2f975620cbd0e6d0e3936d8c0ac39f65b5ed045f7f6769ba6dd52
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
