# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/asio
    REF boost-1.65.1
    SHA512 e538bb6893a5427c9b912e76121d95e6b6c63324dda033eceb05018377827fe0c7596f292ecbf6dc26cc1dfd67955ecf7ce62f5549f46e474a73d52014ed4c95
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
