# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/iterator
    REF boost-1.65.1
    SHA512 1d867783cbe3487129752a7db199a5fba5a2fe176cec485e2ea3ec285a9e1279698ed0e21cc5b2f2ec9e757af388bb458befa2e5585c5a082b860639d558272e
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
