# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/program_options
    REF boost-1.65.1
    SHA512 94f86fa7b765c6c7da7dd4e0672af9f61d5f557ce0c5c7db6a38bd7507933db85eb120642a5795ae0f7650ac80ca07331ef2f52ba22c3e82cb369de8cf7299ca
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
