# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/msm
    REF boost-1.65.1
    SHA512 7998024dd70252f607d7812697127db7d36bf8cca11fde083460ef7cf2bb315c1ccb2091a51c6aa20c4f16f4835bd282fef50240a946226bf2d38c5a2fc0d311
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
