# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/intrusive
    REF boost-1.65.1
    SHA512 2cd18cc9a1e82f9cd8404ca4846be44191b32dfc4c8a030c214a50ab5f0b8a827278f7c6f1ff8ca13dac4693c314abd43fab0474edb9b12bb4c282d4bf2541c7
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
