# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/numeric_conversion
    REF boost-1.65.1
    SHA512 72a5bcb7ab3640d738062f6efde5674c2f42f5c00e0328114a06fe5df15c48d629b076ce8e85065a34c5c9b80a366768a129491c0f9bd7bfde49a597301abd2f
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
