# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/coroutine2
    REF boost-1.65.1
    SHA512 96dfa75356072993d238e0d7977f4ac71852428e26844007bcfe810731e2def11492f6b883de966ec2eb8895f7de9977cdb35c3d60ba71da4cbb530b5714639f
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
