# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/any
    REF boost-1.65.1
    SHA512 e0db03e0c5298792d365c4528217747e1eab462d7986bcbf6dfc28529442a025a21387d9ba3c8f8e2f7e057657e348d215397004e33fde712db92541c354d617
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
