# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/units
    REF boost-1.65.1
    SHA512 134e24435cfcdf1772dc1df9ed0439499aeed6c5ae4c30c4ac1515cbe38516b5a43152928ef5e69d7f70dfdcc58c00fb28a85463a5691b84c56cd70f02014856
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
