# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/format
    REF boost-1.65.1
    SHA512 c8c20cb839224569e7efe82fdd6e13bdcccec6759ecd7631e2a6495048efb7073de30dc27ae69adc47226775c617b3b235385d25da758cd6adad76650482e2fa
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
