# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/regex
    REF boost-1.65.1
    SHA512 84cedc5f11453597beaf607d49cd56895966f6eb74e8435b7aa5f90d20ff99665af3905cd039a1634af6b5fd55c55cccb642412636abfc221bfec53cd0ef7984
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
