# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/xpressive
    REF boost-1.65.1
    SHA512 77fd485b787e4f77ac3329297091c4d9b3b2e8587d37d937680101b62eea51c442b7e8a08ea996cb8eeb70148688220192862675de0b9f70d60eaf06cb625f24
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
