# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/io
    REF boost-1.65.1
    SHA512 38b19d3cdfebbf59c5ecc4b149239ef263040bdd30219ba7cd0cfe0f9c9b57100b7e019bc2f6851f74d0b1f3ca426d9b6162603579a66dd412893512555a7a08
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
