# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/assign
    REF boost-1.65.1
    SHA512 a5fa9728719b63d41e6a2a354882148aaf97fd01a1b793777d8f892a3a09221c6cc287385f878347d1f5a282522c5588dc277b28a856f1b7c03059cffbff6e8c
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
