# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/range
    REF boost-1.65.1
    SHA512 40c9444c929f7379d2830193597c2faaad626b475a2c4dc69a470f2f6ee2a53166945e0c609e5631f434dddd14c33e065ff7fef1e5eeb2861d1c87a4a3cc7d89
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
