# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/fusion
    REF boost-1.65.1
    SHA512 06b4e2812d63debb6101c245bf30bffa53616f9402d1954025412a8998cf5f7e180ccd31ef40279eb7b1ce5f69ba6f51cfefe90b9fb7732abe35d5e573878303
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
