# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/detail
    REF boost-1.65.1
    SHA512 e572cafd13739f24aa58a4ed86d92af884471c67956ac1472d9919824f217f467324451f6a44825bffaf58f78b7e7540c5d1915b2390816a467d60ceccfd1780
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
