# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/spirit
    REF boost-1.65.1
    SHA512 973e94c37864083c01d8590edd18be1fc1321ebc0c1ed7a452729bab201ce84adf3a7763c488d8ea4c79fda0867a80ab347dd930c75cc65001cab98d876a0073
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
