# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/function
    REF boost-1.65.1
    SHA512 24252ef28cb5b9ffe9e9bde3a1625854200a537ba7b7313b890a7d2479f7f8c426f95c8bf788b11755780d3e5d2324afc63a53e2ec5374aa10d3e1945d378abf
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
