# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/lambda
    REF boost-1.65.1
    SHA512 3ab8261cee1378ed9649c5289d0fbfa32c0af2c983a117a71d97c90f758e5df7262e9829027404b6d7303af5c1cf1f114c2b890363ef0988b7697291f4cb3300
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
