# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/config
    REF boost-1.65.1
    SHA512 bb5a75d59255999fd8d9942b35b6fe1d2caa2ad427e707c4cd91d8c69e930d3ff42a7faab44e05b319a0082d05ea2176cb2f937930eda7b87b1d67308ad21d5f
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
