# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/integer
    REF boost-1.65.1
    SHA512 85de196ccfc3a85c8c45856f8bad5a34da5a5c74ae16f39c970d0663ec22e6aedec65de7b536b703a7d76cceda574e83b4ebd4780510cf5e407ec62099e8aa0b
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
