# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/poly_collection
    REF boost-1.65.1
    SHA512 173d15b93b52026aee5ae9d32921620a80887b220c59c5bfd8c92f621eb56a9f0f719b3aec964a10aa76fcaf7333d9cad55114f51e2803425205cdbec99574db
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
