# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/winapi
    REF boost-1.65.1
    SHA512 912c3409c0a972990218078a31a99b61fd03793fa84660340f839d11fc1742239fe1f9d65175b0cf05e72c082de6a5cd62050490adbcd3c01a4da39ecbdcf149
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
