# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/lockfree
    REF boost-1.65.1
    SHA512 a482fb24ddf0a708908bece567f762ab2091bdd105e21d96b9f8c2e86a54108f17bac65d6b6d1ca98636bf19fa37f84bc1011a097940c6206b415bf38974ddce
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
