# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/context
    REF boost-1.65.1
    SHA512 2154abc5a3f6fde3b7ea2be7883b17d51b2607ea8985514d9b3a3c3f9387f884cb49779b67333f5211224d8878659aad5bb8a61d7464ee3c81eaf6a16a3fc7c3
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
