# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/bind
    REF boost-1.65.1
    SHA512 c8db2da8e2cab19f575d6eedb0053cf72adce3656e585eed31e5693e5839c469022a40d95e75abb412608ce4d598680b357796c2601cc645d38c205e5cb2c62a
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
