# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/disjoint_sets
    REF boost-1.65.1
    SHA512 ceadd2466b13c3bf29f804e1247ba8ce404fe3bc8c2bbf012ede73e93758216173971ac0fb48c7e842ebb9319e30920d63dfd4b2a02f859480d0e5d48ec1a58a
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
