# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/wave
    REF boost-1.65.1
    SHA512 c269f553272142e793e3224ac90953d2852c576a5526308c9c928c2e39aabce1896f1373fa57458be7ba555541169c74beb62d8ce2671c26dc979599d7bdfdc8
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
