# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/polygon
    REF boost-1.65.1
    SHA512 f0826a76b45bf9cc2ef13debce9b9df61cbba1cefcbdc63eddd79d4b0fb85001c03c0a8d22d87104d26741b2ea82ff3fedab961418038f365f74c433ddc20c80
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
