# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/filesystem
    REF boost-1.65.1
    SHA512 03402d5870119525768646cd84b87998f6f19533e11ced1923b4209b1e42d5a1d3cf3b8fa5ce3aa59be1c2d924d54189ce6d45a2cc594c46f68541aaa78cf4a3
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
