# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/test
    REF boost-1.65.1
    SHA512 4806209af5cca102c97fc01dd8c59a6dc263882e4704c13d17cae1e2748a0f26f1b12fd9669f712b6a29a69ab0b6ca9a4a756f6ca26a9615c4f2ab3c2797f039
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
