# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/static_assert
    REF boost-1.65.1
    SHA512 064aa86b1ecd94f3a28a71bbd720d9cd6470cb87ba1dd5b13874459331ea37695578a936b8315c7958088e472cb54a921cc230948880506ea89e4e72af7e65fb
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
