# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/endian
    REF boost-1.65.1
    SHA512 941fbe10f889e01d86d57177a6f4032682e5ad79d7b3864682aeec5fcbd6e13e79d613a795ae5788edfd792945bec3ee1156de52ed89e50933a2886792eddd3c
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
