# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/conversion
    REF boost-1.65.1
    SHA512 c3e8c5b72a709690865e929f3e24b4abc14143d2e65926872800b9a0ec0c4c92d06599caee4341210eae4348598efa338bd673764a2e6b4b1ce2e778a8f71356
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
