# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/assert
    REF boost-1.65.1
    SHA512 3b40e3051efe41c65a8dd3e0abc92fc5a73a72b126ea91124c72ea22ee6829ced58243b6d28b1e07c9f012a0145c60e73e2d81d1f45b54ec07d41540786fa9cb
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
