# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/multiprecision
    REF boost-1.65.1
    SHA512 fae7ce08306f07d23dbf6497b9ec3428c415da1bd49978c94ce9f36f4e64faca080539a3244ee46e336018cb188999d8f29eefea4137c4b6ca077566516dc021
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
