# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/foreach
    REF boost-1.65.1
    SHA512 7ded4fc4c5579f017dc64e2a7fd73c248f348defed2d2419fddb9cdb374553e59cf731be05fbff08ec4a7425a495c822f53c5ead94e7b99afec0daaba914bced
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
