# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/statechart
    REF boost-1.65.1
    SHA512 c0b28a9fb6bb0fd8f3b90541b613bb3f18177138263d04848c90b6ec5817c3f066062b2bd3d7219cd1f6f2439f3d430aea1c71fc838351ad77a64bccd97d1ee6
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
