# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/ublas
    REF boost-1.65.1
    SHA512 7bbb36e8f9316f34c8167877f3a9beaa0a98c4e3a7e06593814f4da6706a6903aa827079067cca6522eb5a535aa1855468a678b76e0932a9b6075299bfab7696
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
