# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/qvm
    REF boost-1.65.1
    SHA512 9c876300f08c03f7a12272f8be42891581631a7ab6aab3f21eae539152c4d5c1095488674e353b1667bfdde1e8cdcf375d146adb8d8102bb6048a49ceedeb0d5
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
