# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/bimap
    REF boost-1.65.1
    SHA512 b7ca1ceb28f3f08ebeb7f7e46ea9ce882c2c6b37be5bf770edd99a07e076df42020bece20d23ebec9c620e75a58454336b74dec7405436bdc65d104fbc881a9a
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
