# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/compute
    REF boost-1.65.1
    SHA512 64a0ff582b176449eb4d2afaf3dea754fb72c443cc57809d2fd79bf8a138814d4e78b29e374795b999901d3e8317b00a8cec1ecb751c4253225bed8a9e5f962e
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
