# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/signals
    REF boost-1.65.1
    SHA512 cda26f0c362615cb52597a250457ac7c64f33b2f548cdcd689e529c618437a3068d7963456ff4863c1e3a8f82ca9de5c6c8f61719bed859186b19f7c2139b73d
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
