# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/circular_buffer
    REF boost-1.65.1
    SHA512 b1b8e5f82c3fa65c34efdd2641b74a554ed5a08b8487ed85ae5e41797b70e121570a40b561bfa28d701414a4668e69fbc75af64c845b4746e1a9488f690e43c1
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
