# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/mpi
    REF boost-1.65.1
    SHA512 44dbf02361bd6889642c8af688f2fe149174c50402287884327cc7e31d968e3e1903b4e3acc42b3deaeed350b79eba809bb9f9c5baaa1fb8c12b0f8c66fea207
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
