# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/accumulators
    REF boost-1.65.1
    SHA512 0622092790da58be65c14ffbdde089cda38bb43aebc6f1339c5df1947be83166ccf90999c14b8b1537f83ca1e90f7e2cd9004b9990b395f42c83c5bbb1c62700
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
