# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/preprocessor
    REF boost-1.65.1
    SHA512 b63f59a634a7cb2f1a929b618480da331cf2d58e589b911925b677977b5507f6c115d66a09da1e4ce14724e84c78c8a384374b88ee0de152088862e7588f69a7
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
