# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/geometry
    REF boost-1.65.1
    SHA512 b1e5ee67e5ea0a0f6ff6a6a9950edea5331badcf5f3a4619b972999cd0fa414c3924cd9fe135170496b2d23127f39ef1aef02408bceb0a4af152fd35cdd4596e
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
