# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/dynamic_bitset
    REF boost-1.65.1
    SHA512 bdbbcbe9052fce269744b5f33353262628b8fcb7fc328be96b469d21bcb27775dd943e2a09e476f96a5f71ee7dd4d9c5c78bf26cd941c212cc904395de705723
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
