# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/tokenizer
    REF boost-1.65.1
    SHA512 a52436a3deebd1ef0dfba85a4d36cc8850f8ac539663037b3c2d2e94c29ab4b2096112537f14c0e9176728e626ba6e5dc02f625cdf8018f273c92be6a1e4f5c2
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
