# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/process
    REF boost-1.65.1
    SHA512 04a6303f38b449fa3d1b4c8b43ea44c814134d56545f1c70a62252290ca4aa829ab95ffbf78f00930d352a4962917d307a95547a7380d2daf3881277d89a9246
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
