# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/timer
    REF boost-1.65.1
    SHA512 36d87a9c0e7491e41131390348c0de50d97b063867b78bc6dc7a21772873f9a325031ea521db4cc00e5d3612a3c65fb7b33ff39e7afd7d77523c2982fc77c460
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
