# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/convert
    REF boost-1.65.1
    SHA512 684d41b966fd9297413292fd012656df732f155521b31f7ee97cd3199c31e3ac27e81e42d9bcfbe06efc241f986f16e73f22ad4469b1bb02eb94308f11495cdd
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
