# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/typeof
    REF boost-1.65.1
    SHA512 5c6eb07e46d5fd74913f2d1c4f86caa02d2464d9f552ff1b3592a1b460cd34fdaba10641b28fb9d1e0abb9d33334048f99bd56e1b97e2d961f55613e48f3a054
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
