# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/local_function
    REF boost-1.65.1
    SHA512 8440e8a8a6b2be94ba24420d25b0b68b5808306a96076034108ba89da26ac15d3504677695e4ce2b44dadcdeb160f6b4faccba3a85ff9f35bc566fdc83f91994
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
