# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/signals2
    REF boost-1.65.1
    SHA512 d219eb4a47871e8917f56744c9b9097cfcaba3da01156aa46ebbb61376cd93735a924378fab9daf531616a2117530857e36b3180b49c1f93c1595f5b2093971b
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
