# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/pool
    REF boost-1.65.1
    SHA512 f2025d731362d5a7326448316eabd9c79876693e1d6ebe8d0e08dfd66ce689029243fa2ad0bff662d9e6b8135c825b1376469b44d7bf88efb7ce179fc598f356
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
