# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/concept_check
    REF boost-1.65.1
    SHA512 142b886ef0ce8aa1bfc735764b8b7fbcd1995135457a1c7a75b451b642a01615ef7c86842877f488b64beebb42143c8b6f67d53f34b472f31cf09ea33f30c346
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
