# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/math
    REF boost-1.65.1
    SHA512 194a103dfc68abfbb7e74eb8c54ce6c9edadd8d1180a3976011fd755ba301ef9332916699101dcac8db6bcb9c6efedd20c14e7f971fb085c57b592082a90f48e
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
