# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/function_types
    REF boost-1.65.1
    SHA512 8c3750b0b2d88fa5e6c9c866313ad9749f8d69a256412389d03d5687acc4f45ef52682b8a195fee7f8bf810bc370ad2c0e2dbbb256f65bc95bb6c5bba3718957
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
