# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/algorithm
    REF boost-1.65.1
    SHA512 5d78c969cabbc7fbe0d7712fce9d6ceb4bcca162137ced1149c09283ae54e70308a4424373d6c802ca876a8bf429630a4c68a86b3344a059d0394feaeb0dd0f8
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
