# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/mpl
    REF boost-1.65.1
    SHA512 49ce489ce517886880ccbbebd917a6ca9f3f479311ce8f0b01c775394bc5b83c148b310acf67f23e9fab8eb1617db3ea6b5275ba8f89411fbd52e2416ff6519b
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
