# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/flyweight
    REF boost-1.65.1
    SHA512 f84d3f727a171d17b2f6ab0362d2bf8813e093a2621ed9f8e352d08016fef1cf03774560b3de00d29e25f08c7d154941fe99e756aaba9a99f79e6209346a853e
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
