# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/property_tree
    REF boost-1.65.1
    SHA512 1ee02b7a366573197e7e0c86fdab4102bed97c40f13ff9c7bd5b3bab187ab3645b070e90f3e1f24786a8d99383737e9d28eb7bb9ce0e151cab0fc339a4159b01
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
