# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/container
    REF boost-1.65.1
    SHA512 85ca448ad04783c1161f757d2c9791be6aadacd7d0f24ccc899eaae6c6f6b1de530305918fac01a4b7331e2f5037b061ed3a1d49320b03c373954ac5ce6b2c22
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
