# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/metaparse
    REF boost-1.65.1
    SHA512 b1e73796d414d2604c5412ca09b5afbf7450691b39c3ed5104fa40de85f1d75a80b6f07ab29e37f596c328b6103c36e88834a88a7663d25622c17b315703c307
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
