# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/system
    REF boost-1.65.1
    SHA512 69e5a9dfff0d7451295ca1499c183d9a791b3fcbda780e9f3b64310151efe6d964918a588db366c7bd14fbd307f8d9b3e3f7e1a60c151c274a95d9847c77b688
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
