# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/graph
    REF boost-1.65.1
    SHA512 571190083abcc6ddca788017fcf9a703f11b1a0dd88b0905c44876fbf0c4ff0a4d97b6b170e3495397f0124a18e131f7aadb7712832eef3a7af4ea21efbca8ce
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
