# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/property_map
    REF boost-1.65.1
    SHA512 762b6d3a0e7d1b1d7e38b204ebbcab6f96411f93cc4348bafc3299efbd337bfd1833b78859ed87ed80d112245553d81aacc70cba3fe1559474d32d70c25348ab
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
