# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/interprocess
    REF boost-1.65.1
    SHA512 383be05a8c31172065a5c6ead965155a50a3c6f8dfe3ee6fe17d185c80afe9e0a9feac516b1c59039319b97aefc512da2d7f998715b23d5576b41928bb3c3025
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
