# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/chrono
    REF boost-1.65.1
    SHA512 3d111620de8ae5caf630276b36ae57375729ad7517c0967f0a8071574a5371128c8488416dbae0399a7c49c22cf220ee1b11537fb945114a39f8a3075ad7cea4
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
