# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/unordered
    REF boost-1.65.1
    SHA512 75b6659d6aba97454d1939b47a8d8a8448f969e787707fc9c112ab61a17f2d4f02a36f2474f673127a189ea42a0686868405b3d1a3aa7938c7483d347f5740c0
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
