# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/sort
    REF boost-1.65.1
    SHA512 d906af29ec267758f469739aff02ccf18904e5e5fe256f34ef705bf4c5a8faa9ab45f50ca90838ca7b2998573c5f96dbeb3b52339ba4c31819a61c3574b86f5f
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular.cmake)

boost_modular(
    SOURCE_PATH ${SOURCE_PATH}
    
)
